-- Instructions: Run this SQL script in your Oracle database to create the reservations table
-- You can run this using SQL*Plus, SQL Developer, or any Oracle database client

-- Reservations table for book holds
CREATE TABLE reservations (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    reservation_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'AVAILABLE', 'CANCELLED', 'FULFILLED')),
    notification_sent VARCHAR2(1) DEFAULT 'N' CHECK (notification_sent IN ('Y', 'N')),
    expiry_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES members(member_id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE,
    CONSTRAINT unique_pending_reservation UNIQUE (member_id, book_id)
);

-- Index for better performance
CREATE INDEX idx_reservations_member ON reservations(member_id);
CREATE INDEX idx_reservations_book ON reservations(book_id);
CREATE INDEX idx_reservations_status ON reservations(status);

-- Trigger for updating timestamp
CREATE OR REPLACE TRIGGER update_reservations_timestamp
    BEFORE UPDATE ON reservations
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Verify table creation
SELECT table_name FROM user_tables WHERE table_name = 'RESERVATIONS';

COMMIT;
