-- Library Management System Database Schema

-- Create Members table
CREATE TABLE members (
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(15),
    address VARCHAR2(200),
    membership_type VARCHAR2(20) DEFAULT 'STUDENT' CHECK (membership_type IN ('STUDENT', 'FACULTY', 'STAFF')),
    membership_date DATE DEFAULT SYSDATE,
    status VARCHAR2(10) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Books table
CREATE TABLE books (
    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR2(20) UNIQUE,
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(100) NOT NULL,
    publisher VARCHAR2(100),
    publication_year NUMBER(4),
    category VARCHAR2(50),
    total_copies NUMBER(3) DEFAULT 1,
    available_copies NUMBER(3) DEFAULT 1,
    price NUMBER(10,2),
    description CLOB,
    status VARCHAR2(20) DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'UNAVAILABLE', 'LOST', 'DAMAGED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Transactions table (for book issues and returns)
CREATE TABLE transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    issue_date DATE DEFAULT SYSDATE,
    due_date DATE,
    return_date DATE,
    fine_amount NUMBER(10,2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ISSUED' CHECK (status IN ('ISSUED', 'RETURNED', 'OVERDUE', 'LOST')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES members(member_id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE
);

-- Create Admins table
CREATE TABLE admins (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    role VARCHAR2(20) DEFAULT 'LIBRARIAN' CHECK (role IN ('SUPER_ADMIN', 'LIBRARIAN')),
    status VARCHAR2(10) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Fine History table
CREATE TABLE fine_history (
    fine_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    fine_amount NUMBER(10,2) NOT NULL,
    fine_reason VARCHAR2(100),
    paid_date DATE,
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PAID', 'WAIVED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (transaction_id) REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES members(member_id) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_members_email ON members(email);
CREATE INDEX idx_members_status ON members(status);
CREATE INDEX idx_books_title ON books(title);
CREATE INDEX idx_books_author ON books(author);
CREATE INDEX idx_books_isbn ON books(isbn);
CREATE INDEX idx_books_status ON books(status);
CREATE INDEX idx_transactions_member ON transactions(member_id);
CREATE INDEX idx_transactions_book ON transactions(book_id);
CREATE INDEX idx_transactions_status ON transactions(status);
CREATE INDEX idx_transactions_due_date ON transactions(due_date);

-- Create triggers for updating timestamps
CREATE OR REPLACE TRIGGER update_members_timestamp
    BEFORE UPDATE ON members
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER update_books_timestamp
    BEFORE UPDATE ON books
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER update_transactions_timestamp
    BEFORE UPDATE ON transactions
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER update_admins_timestamp
    BEFORE UPDATE ON admins
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Insert default admin user (password: admin123)
INSERT INTO admins (username, email, password_hash, first_name, last_name, role) 
VALUES ('admin', 'admin@library.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'System', 'Administrator', 'SUPER_ADMIN');

UPDATE admins SET password_hash = '$2a$10$CEsDGfM041K/uaANgVaYh.Bm3iaP8ENvhQsCzbu3jrNDcqTO5D4KK' WHERE username = 'admin';
COMMIT;

-- Insert sample data
INSERT INTO members (first_name, last_name, email, phone, address, membership_type) VALUES
('John', 'Doe', 'john.doe@email.com', '1234567890', '123 Main St, City', 'STUDENT');
INSERT INTO members (first_name, last_name, email, phone, address, membership_type) VALUES
('Jane', 'Smith', 'jane.smith@email.com', '0987654321', '456 Oak Ave, City', 'FACULTY');
INSERT INTO members (first_name, last_name, email, phone, address, membership_type) VALUES
('Bob', 'Johnson', 'bob.johnson@email.com', '1122334455', '789 Pine St, City', 'STAFF');

INSERT INTO books (isbn, title, author, publisher, publication_year, category, total_copies, available_copies, price)
VALUES ('978-0134685991', 'Effective Java', 'Joshua Bloch', 'Addison-Wesley', 2018, 'Programming', 3, 3, 45.99);
INSERT INTO books (isbn, title, author, publisher, publication_year, category, total_copies, available_copies, price)
VALUES ('978-0132350884', 'Clean Code', 'Robert C. Martin', 'Prentice Hall', 2008, 'Programming', 2, 2, 39.99);
INSERT INTO books (isbn, title, author, publisher, publication_year, category, total_copies, available_copies, price)
VALUES ('978-0201633610', 'Design Patterns', 'Gang of Four', 'Addison-Wesley', 1994, 'Programming', 2, 2, 49.99);
INSERT INTO books (isbn, title, author, publisher, publication_year, category, total_copies, available_copies, price)
VALUES ('978-1260143634', 'Database System Concepts', 'Abraham Silberschatz', 'McGraw-Hill', 2019, 'Database', 4, 4, 89.99);
INSERT INTO books (isbn, title, author, publisher, publication_year, category, total_copies, available_copies, price)
VALUES ('978-0262033848', 'Introduction to Algorithms', 'Thomas H. Cormen', 'MIT Press', 2009, 'Computer Science', 3, 3, 79.99);

COMMIT;
